######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 27 13:25:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . GeneratedFiles
INCLUDEPATH += .

# Input
HEADERS += qtlvba.h \
    feedbackwidget.h \
    recoverpassword.h \
    logview.h \
    passwordcheck.h \
    systemsetting.h \
    textlogview.h \
    passwordcheck2.h \
    screenlogview.h \
    passwordcheck3.h
FORMS += qtlvba.ui \
    feedbackwidget.ui \
    recoverpassword.ui \
    logview.ui \
    passwordcheck.ui \
    systemsetting.ui \
    textlogview.ui \
    passwordcheck2.ui \
    screenlogview.ui \
    passwordcheck3.ui
SOURCES += main.cpp qtlvba.cpp \
    feedbackwidget.cpp \
    recoverpassword.cpp \
    logview.cpp \
    passwordcheck.cpp \
    systemsetting.cpp \
    textlogview.cpp \
    passwordcheck2.cpp \
    screenlogview.cpp \
    passwordcheck3.cpp
RESOURCES += qtlvba.qrc
RC_FILE = myapp.rc

